version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    command: celery -A celerytest worker -n w1 --loglevel=info
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULTS_URL=redis://redis:6379/1
